test

diff --git a/scaffold/tugboat/config.example.yml b/scaffold/tugboat/config.example.yml
--- a/scaffold/tugboat/config.example.yml
+++ b/scaffold/tugboat/config.example.yml
@@ -56,6 +56,10 @@ services:
         apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
         docker-php-ext-configure gd --with-jpeg --with-freetype && docker-php-ext-install gd
 
+        # Install drush-launcher, if desired.
+        wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
+        chmod +x /usr/local/bin/drush
+
       # Commands that import files, databases,  or other assets. When an
       # existing preview is refreshed, the build workflow starts here,
       # skipping the init step, because the results of that step will
@@ -84,12 +88,12 @@ services:
         # vendor/bin/task drupal:import-db
 
         # Install
-        drush site:install --standard-profile
-
-        if [[ "drush site:install --standard-profile" == "NULL" ]]; then
-          echo -e "FATAL ERROR: Not installed"
-          exit 1
-        fi
+        echo "I am running site install"
+        drush site:install
+#        if [[ "drush site:install --standard-profile" == "NULL" ]]; then
+#          echo -e "FATAL ERROR: Not installed"
+#          exit 1
+#        fi
 
       # Commands that build the site. This is where you would add things
       # like feature reverts or any other drush commands required to
