update configure gd and sire install

diff --git a/scaffold/tugboat/tugboat.acquia-example.yml b/scaffold/tugboat/tugboat.acquia-example.yml
--- a/scaffold/tugboat/tugboat.acquia-example.yml
+++ b/scaffold/tugboat/tugboat.acquia-example.yml
@@ -104,3 +104,12 @@ services:
   memcached:
 
     image: tugboatqa/memcached:1
+
+    commands:
+
+      update: |
+
+        if [[ "tugboatqa/memcached:1" == "NULL" ]]; then
+          echo -e "FATAL ERROR: Not installed"
+          exit 1
+        fi
diff --git a/scaffold/tugboat/tugboat.pantheon-example.yml b/scaffold/tugboat/tugboat.pantheon-example.yml
--- a/scaffold/tugboat/tugboat.pantheon-example.yml
+++ b/scaffold/tugboat/tugboat.pantheon-example.yml
@@ -34,28 +34,15 @@ services:
         # Install prerequisite packages
         apt-get update
         apt-get install -y mariadb-client libldap2-dev
-
         # Install drush-launcher
         wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.10.1/drush.phar
         chmod +x /usr/local/bin/drush
-
         # Link the document root to the expected path. Tugboat uses /docroot
         # by default. So, if Drupal is located at any other path in your git
         # repository, change that here. This example links /web to the docroot
         [ -d "${DOCROOT}" ] || ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
-
         docker-php-ext-install opcache
         a2enmod headers rewrite
-
-        # WebP
-        apt-get install -y libwebp-dev libwebp6 webp libmagickwand-dev
-        docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp
-        docker-php-ext-install gd
-
-        # Configure GD
-        apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
-        docker-php-ext-configure gd --with-jpeg --with-freetype && docker-php-ext-install gd
-
       # Commands that import files, databases,  or other assets. When an
       # existing preview is refreshed, the build workflow starts here,
       # skipping the init step, because the results of that step will
@@ -63,34 +50,20 @@ services:
       update: |
         set -eux
         echo "Updating..."
-
         # We intentionally do not set up syncing of static assets, as we have
         # decided to always use Stage File Proxy:
         # https://architecture.lullabot.com/adr/20210729-stage-file-proxy/
-
         # Set up permissions for the files directories.
         chgrp -R www-data "${DOCROOT}/sites/default/files"
         chmod -R g+w "${DOCROOT}/sites/default/files"
         chmod 2775 "${DOCROOT}/sites/default/files"
-
         composer install
-
         # Install Drupal using the standard profile.
         vendor/bin/task drupal:install
-
         # To use an existing site, add the appropriate environment variables
         # as document at <LINK> and instead run:
         # vendor/bin/task <provider>:fetch-db
         # vendor/bin/task drupal:import-db
-
-        # Install
-        drush site:install --standard-profile
-
-        if [[ "drush site:install --standard-profile" == "NULL" ]]; then
-          echo -e "FATAL ERROR: Not installed"
-          exit 1
-        fi
-
       # Commands that build the site. This is where you would add things
       # like feature reverts or any other drush commands required to
       # set up or configure the site. When a preview is built from a
@@ -101,7 +74,6 @@ services:
         set -eux
         vendor/bin/task drupal:update
         vendor/bin/drush user:login
-
   # What to call the service hosting MySQL. This name also acts as the
   # hostname to access the service by from the php service.
   mariadb:
@@ -117,3 +89,16 @@ services:
       # already be present.
       update:
         - echo "Nothing to do as we import databases from the Drupal service."
+
+  redis:
+
+    image: tugboatqa/redis:7
+
+    commands:
+
+      update: |
+
+        if [[ "tugboatqa/redis:7" == "NULL" ]]; then
+          echo -e "FATAL ERROR: Not installed"
+          exit 1
+        fi
