test

diff --git a/scaffold/tugboat/tugboat.acquia-example.yml b/scaffold/tugboat/tugboat.acquia-example.yml
--- a/scaffold/tugboat/tugboat.acquia-example.yml
+++ b/scaffold/tugboat/tugboat.acquia-example.yml
@@ -105,11 +105,11 @@ services:
 
     image: tugboatqa/memcached:1
 
-    commands:
-
-      update: |
-
-        if [[ "tugboatqa/memcached:1" == "NULL" ]]; then
-          echo -e "FATAL ERROR: Not installed"
-          exit 1
-        fi
+#    commands:
+#
+#      update: |
+#
+#        if [[ "tugboatqa/memcached:1" == "NULL" ]]; then
+#          echo -e "FATAL ERROR: Not installed"
+#          exit 1
+#        fi
diff --git a/scaffold/tugboat/tugboat.pantheon-example.yml b/scaffold/tugboat/tugboat.pantheon-example.yml
--- a/scaffold/tugboat/tugboat.pantheon-example.yml
+++ b/scaffold/tugboat/tugboat.pantheon-example.yml
@@ -94,11 +94,11 @@ services:
 
     image: tugboatqa/redis:7
 
-    commands:
-
-      update: |
-
-        if [[ "tugboatqa/redis:7" == "NULL" ]]; then
-          echo -e "FATAL ERROR: Not installed"
-          exit 1
-        fi
+#    commands:
+#
+#      update: |
+#
+#        if [[ "tugboatqa/redis:7" == "NULL" ]]; then
+#          echo -e "FATAL ERROR: Not installed"
+#          exit 1
+#        fi
