Add tasks for setting up Nightwatch and upgrade Selenium

diff --git a/tasks/test.yml b/tasks/test.yml
--- a/tasks/test.yml
+++ b/tasks/test.yml
@@ -140,10 +140,104 @@ tasks:
         elif [ -f ".stylelintrc.json" ] && [ -f "package-lock.json" ]; then
           npm run stylelint "**/*.{css,scss,sass}" --fix
         fi
+  nightwatch:check:
+    #desc: Verifies Nightwatch is setup correctly
+    cmds:
+      - |
+        if [ ! -f "package.json" ]; then
+          echo "No package.json exists, please run test:nightwatch:setup"
+        fi
+      - |
+        if [ "$IS_DDEV_PROJECT" == "true" ]; then
+          DATABASE_FIREFOX="CREATE DATABASE IF NOT EXISTS firefox";
+          DATABASE_CHROME="CREATE DATABASE IF NOT EXISTS chrome";
+          if ! grep -q "$DATABASE_FIREFOX" .ddev/config.yaml; then
+            echo "No Firefox container found, please run test:nightwatch:setup"
+            exit 1
+          fi
+          if ! grep -q "$DATABASE_CHROME" .ddev/config.yaml; then
+            echo "No Chrome container found, please run test:nightwatch:setup"
+            exit 1
+          fi
+        fi
+      - |
+        if [ "$IS_DDEV_PROJECT" == "true" ]; then
+          HOST_FIREFOX="NIGHTWATCH_DRUPAL_URL_FIREFOX=https://drupal_firefox"
+          HOST_CHROME="NIGHTWATCH_DRUPAL_URL_CHROME=https://drupal_chrome"
+          if ! grep -q "$HOST_FIREFOX" .ddev/config.yaml; then
+            echo "No Firefox hostname found, please run test:nightwatch:setup"
+            exit 1
+          fi
+          if ! grep -q "$HOST_CHROME" .ddev/config.yaml; then
+            echo "No Chrome hostname found, please run test:nightwatch:setup"
+            exit 1
+          fi
+        fi
+      - echo "Nightwatch appears to be setup correctly"
+  nightwatch:setup:
+    desc: Sets up Nightwatch
+    interactive: true
+    cmds:
+      - |
+        PACKAGES="nightwatch nightwatch-accessibility @lullabot/nightwatch-drupal-commands"
+        if [ ! -f "package.json" ]; then
+          echo -n "No package.json exists, would you like to use yarn1, npm, or yarn? "
+          read -r PACKAGE_MANAGER
+          if [ "$PACKAGE_MANAGER" == "npm" ]; then
+            if [ "$IS_DDEV_PROJECT" == "true" ]; then
+              sudo npm update -g
+            fi
+            npm init -y
+            npm install $PACKAGES --save-dev
+          elif [ "$PACKAGE_MANAGER" == "yarn1" ]; then
+            yarn set version classic
+            yarn init -y
+            yarn add $PACKAGES --dev
+          elif [ "$PACKAGE_MANAGER" == "yarn" ]; then
+            yarn set version berry
+            yarn init
+            yarn add $PACKAGES --dev
+          else
+            echo "Sorry I'm not aware of that package manager. Please first init package.json with it yourself manually."
+          fi
+        else
+          if [ -f "package-lock.json" ]; then
+            npm install $PACKAGES --save-dev
+          elif [ -f "yarn.lock" ]; then
+            yarn add $PACKAGES --dev
+          else
+            echo "package.json found but unable to figure out which package manager is in use"
+            echo "Please manually install $PACKAGES"
+            exit 1;
+          fi
+        fi
+
+        if [ "$IS_DDEV_PROJECT" == "true" ]; then
+          echo 'Add the following to post-start hooks to .ddev/config.yaml:';
+          echo ""
+          echo "hooks:";
+          echo "  post-start:";
+          echo "    - exec: mysql -uroot -proot -hdb -e \"CREATE DATABASE IF NOT EXISTS firefox; GRANT ALL ON firefox.* TO 'db'@'%';\"";
+          echo "    - exec: mysql -uroot -proot -hdb -e \"CREATE DATABASE IF NOT EXISTS chrome; GRANT ALL ON chrome.* TO 'db'@'%';\"";
+          echo ""
+          echo "Run:"
+          echo ""
+          echo "ddev config --web-environment=\"NIGHTWATCH_DRUPAL_URL_FIREFOX=https://drupal_firefox,NIGHTWATCH_DRUPAL_URL_CHROME=https://drupal_chrome\""
+          echo "ddev config --additional-hostnames=\"*.$DDEV_SITENAME\""
+          echo "ddev restart"
+        fi
   nightwatch:
     desc: Runs Nighwatch functional browser tests
+    deps: [nightwatch:check]
     env:
       NIGHTWATCH_ENV: 'firefox,chrome'
     cmds:
-      - yarn
-      - yarn nightwatch --env $NIGHTWATCH_ENV {{.CLI_ARGS}}
+      - |
+        if [ -f "package-lock.json" ]; then
+          npm run nightwatch --env $NIGHTWATCH_ENV {{.CLI_ARGS}}
+        elif [ -f "yarn.lock" ]; then
+          yarn nightwatch --env $NIGHTWATCH_ENV {{.CLI_ARGS}}
+        else
+          echo "Unable to figure out which package manager is in use"
+          exit 1;
+        fi
