ISSUE-204: to not continue [skip ci]

diff --git a/scaffold/github/actions/acquia/deploy/action.yml b/scaffold/github/actions/acquia/deploy/action.yml
--- a/scaffold/github/actions/acquia/deploy/action.yml
+++ b/scaffold/github/actions/acquia/deploy/action.yml
@@ -95,6 +95,9 @@ runs:
         # Extract the environment.uri value
         echo "acquia_env_uri=$(echo "$ALIASES_YML_CONTENT" | yq e ".${ENVIRONMENT}.uri" -)" >> $GITHUB_ENV
 
+        echo "::error::Debugging, not continuing"
+        exit 1;
+
     - name: Push to Acquia
       uses: ./.github/actions/drainpipe/acquia/push
       with:
