#621 adding sync and update task to the test

diff --git a/.github/workflows/TestTugboat.yml b/.github/workflows/TestTugboat.yml
--- a/.github/workflows/TestTugboat.yml
+++ b/.github/workflows/TestTugboat.yml
@@ -66,13 +66,17 @@ jobs:
           # After the Taskfile is created,
           # we can add the build:tugboat and tugboat:online steps.
 
-          echo "  tugboat:update:" >> Taskfile.yml
+          echo "  tugboat:sync:" >> Taskfile.yml
           echo "    cmds:" >> Taskfile.yml
-          echo "      - echo \"Tugboat update\"" >> Taskfile.yml
+          echo "      - echo \"Tugboat sync\"" >> Taskfile.yml
 
           echo "  tugboat:build:" >> Taskfile.yml
           echo "    cmds:" >> Taskfile.yml
           echo "      - echo \"Tugboat build\"" >> Taskfile.yml
+
+          echo "  tugboat:update:" >> Taskfile.yml
+          echo "    cmds:" >> Taskfile.yml
+          echo "      - echo \"Tugboat update\"" >> Taskfile.yml
 
           echo "  tugboat:online:" >> Taskfile.yml
           echo "    cmds:" >> Taskfile.yml
@@ -80,13 +84,18 @@ jobs:
 
           ddev composer install
 
-          if ! grep -q './vendor/bin/task tugboat:update' .tugboat/steps/2-update.sh; then
-            echo "tugboat:update not found in .tugboat/steps/2-update.sh"
+          if ! grep -q './vendor/bin/task tugboat:sync' .tugboat/steps/2-update.sh; then
+            echo "tugboat:sync not found in .tugboat/steps/2-update.sh"
             exit 1
           fi
 
           if ! grep -q './vendor/bin/task tugboat:build' .tugboat/steps/3-build.sh; then
             echo "tugboat:build not found in .tugboat/steps/3-build.sh"
+            exit 1
+          fi
+
+          if ! grep -q './vendor/bin/task tugboat:update' .tugboat/steps/3-build.sh; then
+            echo "tugboat:update not found in .tugboat/steps/3-build.sh"
             exit 1
           fi
 
